# Step 1: Build React app
FROM node:20-alpine AS build


WORKDIR /app

# Install dependencies
COPY package*.json ./frontend1/package.json
RUN npm install

# Copy rest of the code and build React app
COPY . .
RUN npm run build

# Step 2: Serve with Nginx
FROM nginx:alpine

# Copy built React app into Nginx webroot
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80 for Nginx
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
